theme = "hyde"
baseURL = "https://pace577.github.io/literary-manifesto/"
languageCode = "en-us"
title = "The LAS Manifesto"

[Menus]
  main = [
      {Name = "About me", URL = "/about-me"},
  ]

[params]
  description = "Prabhat Reddy"
  themeColor = "theme-base-08"
  layoutReverse = false
  copyright = "CC/SA"
